/* Do not edit this file. This file is generated with @creadigme/aurelia-stories - 29/04/2022, 11:44:18 */
/* eslint-disable prettier/prettier */
import Aurelia from 'aurelia';
import { Au2Countdown } from './../components/au2-countdown';

// More on default export: https://storybook.js.org/docs/html/writing-stories/introduction#default-export
export default {
  title: 'components/au2-countdown',
  // More on argTypes: https://storybook.js.org/docs/html/api/argtypes
  argTypes: {
    countdown: {"type":"number","control":{"type":"number","step":1},"defaultValue":"0","description":"Countdown","table":{"category":"Properties"}},
    interval: {"type":"number","control":{"type":"number","step":1},"defaultValue":"1","description":"Interval in seconds","table":{"category":"Properties"}},
    onReach: {"type":"object","control":"object","table":{"category":"Properties"}},
    startValue: {"type":"number","control":{"type":"number","step":1},"defaultValue":"10","description":"start value","table":{"category":"Properties"}},
    start: {"type":"object","control":"object","description":"Start the countdown\n\n**@documented** \n","table":{"category":"Methods"}},
    stop: {"type":"object","control":"object","description":"Stop the countdown\n\n**@documented** \n","table":{"category":"Methods"}},
  },
};

// More on component templates: https://storybook.js.org/docs/html/writing-stories/introduction#using-args
const Template = (options) => {
  const host = document.createElement('div');
  host.innerHTML = `<au2-countdown  countdown.bind="countdown"
  interval.bind="interval"
  onReach.bind="onReach"
  startValue.bind="startValue"
  ></au2-countdown>`;
  Aurelia.register(Au2Countdown).enhance({
    host,
    component: options,
  });
  return host;
};

export const DefaultUsage = Template.bind({});
DefaultUsage.args = {};
DefaultUsage.storyName = 'Default usage';
DefaultUsage.parameters = {
  docs: {
    description: {
      component: "Au2 Countdown",
    },
  },
};

const RawTemplate = (options) => {
  const host = document.createElement('div');
  host.innerHTML = options.content;
  Aurelia.register(Au2Countdown).enhance({
    host,
    component: {},
  });
  return host;
};

export const story0 = RawTemplate.bind({});
story0.args = {
  content: "<let finish-stack.bind=\"[]\"></let>\n<au2-countdown view-model.ref=\"countdownVM\" on-reach.call=\"finishStack.push('Let\\'s go')\"></au2-countdown>\n<button click.trigger=\"countdownVM.isActive ? countdownVM.stop() : countdownVM.start()\">${countdownVM.isActive ? 'Stop' : 'Start'}</button>\n<ul><li repeat.for=\"finish of finishStack\">${finish}</li></ul>\n",
};
story0.storyName = "Start at 10";
story0.parameters = {
  docs: {
    description: {
      story: "`button` `simple`\n" + "Countdown sample\n",
    },
  },
};
export const story1 = RawTemplate.bind({});
story1.args = {
  content: "<au2-countdown view-model.ref=\"countdownVM\" start-value.bind=\"100\"></au2-countdown>\n<button click.trigger=\"countdownVM.isActive ? countdownVM.stop() : countdownVM.start()\">${countdownVM.isActive ? 'Stop' : 'Start'}</button>\n",
};
story1.storyName = "Start at 100";
story1.parameters = {
  docs: {
    description: {
      story: "`button` `simple`\n" + "Countdown sample\n",
    },
  },
};
