/* Do not edit this file. This file is generated with @creadigme/aurelia-stories - 29/04/2022, 11:44:18 */
/* eslint-disable prettier/prettier */
import Aurelia from 'aurelia';
import { Au2Button } from './../components/au2-button';

// More on default export: https://storybook.js.org/docs/html/writing-stories/introduction#default-export
export default {
  title: 'components/au2-button',
  // More on argTypes: https://storybook.js.org/docs/html/api/argtypes
  argTypes: {
    action: {"type":"object","control":"object","table":{"category":"Properties"}},
    content: {"type":"string","control":"text","defaultValue":"'Click me'","description":"Content of button","table":{"category":"Properties"}},
    style: {"type":"string","control":"text","description":"Style of button","table":{"category":"Properties"}},
  },
};

// More on component templates: https://storybook.js.org/docs/html/writing-stories/introduction#using-args
const Template = (options) => {
  const host = document.createElement('div');
  host.innerHTML = `<au2-button  action.bind="action"
  content.bind="content"
  style.bind="style"
  ></au2-button>`;
  Aurelia.register(Au2Button).enhance({
    host,
    component: options,
  });
  return host;
};

export const DefaultUsage = Template.bind({});
DefaultUsage.args = {};
DefaultUsage.storyName = 'Default usage';
DefaultUsage.parameters = {
  docs: {
    description: {
      component: "I'm not a button",
    },
  },
};

const RawTemplate = (options) => {
  const host = document.createElement('div');
  host.innerHTML = options.content;
  Aurelia.register(Au2Button).enhance({
    host,
    component: {},
  });
  return host;
};

export const story0 = RawTemplate.bind({});
story0.args = {
  content: "<let state.bind=\"false\"></let>\n<au2-button action.call=\"state = !state\" content=\"${state ? 'Turn me off' : 'Turn me on'}\"></au2-button>\n<div>${state ? '✅' : '☐' }</div>\n",
};
story0.storyName = "Toggle";
story0.parameters = {
  docs: {
    description: {
      story: "`button` `simple`\n" + "A button toggle\n",
    },
  },
};
export const story1 = RawTemplate.bind({});
story1.args = {
  content: "<let state.bind=\"false\"></let>\n<au2-button action.call=\"state = !state\" content=\"${state ? '✅' : '☐'}\"></au2-button>\n<div>${state ? '✅' : '☐' }</div>\n",
};
story1.storyName = "Another story";
story1.parameters = {
  docs: {
    description: {
      story: "`button` `simple` `supra`\n" + "Another story. Look at this sample...\n",
    },
  },
};
